environment:

  matrix:
    - PYTHON: "C:\\Python27"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - PYTHON: "C:\\Python34"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"


install:
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools wheel && %PYTHON%\\python.exe -m pip install ."

build: off

test_script:
  - "%PYTHON%\\python.exe test.py"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
